In [1]:
import sys
from google.colab import drive

drive.mount('/content/drive', force_remount=True)
sys.path.append('/content/drive/MyDrive/Colab_Notebooks/DL_course/Clase_2')

Mounted at /content/drive


In [2]:
import pandas as pd, numpy as np
data = pd.read_csv('/content/drive/MyDrive/Advertising.csv')

In [3]:
data

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [4]:
X = data.iloc[:, 1:4].to_numpy()

print(X.shape)

(200, 3)


In [5]:
X = np.insert(X, 0, np.ones((X.shape[0])), axis = 1)
print(X.shape)

(200, 4)


In [6]:
print(X)

[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]
 [  1.    8.7  48.9  75. ]
 [  1.   57.5  32.8  23.5]
 [  1.  120.2  19.6  11.6]
 [  1.    8.6   2.1   1. ]
 [  1.  199.8   2.6  21.2]
 [  1.   66.1   5.8  24.2]
 [  1.  214.7  24.    4. ]
 [  1.   23.8  35.1  65.9]
 [  1.   97.5   7.6   7.2]
 [  1.  204.1  32.9  46. ]
 [  1.  195.4  47.7  52.9]
 [  1.   67.8  36.6 114. ]
 [  1.  281.4  39.6  55.8]
 [  1.   69.2  20.5  18.3]
 [  1.  147.3  23.9  19.1]
 [  1.  218.4  27.7  53.4]
 [  1.  237.4   5.1  23.5]
 [  1.   13.2  15.9  49.6]
 [  1.  228.3  16.9  26.2]
 [  1.   62.3  12.6  18.3]
 [  1.  262.9   3.5  19.5]
 [  1.  142.9  29.3  12.6]
 [  1.  240.1  16.7  22.9]
 [  1.  248.8  27.1  22.9]
 [  1.   70.6  16.   40.8]
 [  1.  292.9  28.3  43.2]
 [  1.  112.9  17.4  38.6]
 [  1.   97.2   1.5  30. ]
 [  1.  265.6  20.    0.3]
 [  1.   95.7   1.4   7.4]
 [  1.  290.7   4.1   8.5]
 [  1.  266.9  43.8   5. ]
 

In [7]:
Y = data.iloc[:, 4].to_numpy()
print(Y.shape)

(200,)


In [8]:
Y = Y.reshape((Y.shape[0], 1))

In [9]:
print(Y.shape)

(200, 1)


In [10]:
theta = np.random.rand(X.shape[1], 1)
print(theta.shape)

(4, 1)


In [11]:
print(theta)

[[0.04399887]
 [0.83184457]
 [0.00953762]
 [0.3345918 ]]


In [12]:
h = X@theta

print(h.shape)

(200, 1)


$$J(\theta)  = \frac{1}{2m}(X.\theta - Y)^T . (X.\theta - Y)$$

In [13]:
def MSE(X, theta, Y):
  return (1 / 2 * X.shape[0]) * (X@theta - Y).T @ (X@theta - Y)

In [14]:
print(MSE(X, theta, Y))

[[3.7453265e+08]]


$$\begin{bmatrix}
{\theta_0} \\
{\theta_1} \\
.\\
.\\
.\\
{\theta_n}\\
\end{bmatrix}=
\begin{bmatrix}
{\theta_0} \\
{\theta_1} \\
.\\
.\\
.\\
{\theta_n}\\
\end{bmatrix}
-\alpha /m
\begin{bmatrix}
\frac{\partial J(\theta)}{\partial \theta_0} \\
\frac{\partial J(\theta)}{\partial \theta_1} \\
.\\
.\\
.\\
\frac{\partial J(\theta)}{\partial \theta_n}\\
\end{bmatrix}$$


$$
\begin{bmatrix}
\frac{\partial J(\theta)}{\partial \theta_0} \\
\frac{\partial J(\theta)}{\partial \theta_1} \\
.\\
.\\
.\\
\frac{\partial J(\theta)}{\partial \theta_{n}}\\
\end{bmatrix}
=\frac{1}{m}(h_\theta - Y)X^T = \frac{1}{m}(X.\theta - Y)X^T
$$


In [15]:
from tqdm import tqdm

def train(X, Y, theta, learning_rate = 1e-3, epochs = 100):
  for epoch in tqdm(range(epochs)):
    theta = theta - (learning_rate / X.shape[0]) * X.T @ (X@theta - Y)
  return theta


In [16]:
print(MSE(X, theta, Y))
theta = train(X, Y, theta = theta, learning_rate = 5e-5, epochs = 1000000)

print(MSE(X, theta, Y))

[[3.7453265e+08]]


100%|██████████| 1000000/1000000 [00:17<00:00, 55858.23it/s]

[[55682.53748894]]


In [17]:
print(theta)

[[ 2.93693107e+00]
 [ 4.57699933e-02]
 [ 1.88552482e-01]
 [-1.02559828e-03]]
